Sayrix/Ticket-Bot

events/ready.js

Update ready.js | Need reviewers

---

config/config.jsonc
events/interactionCreate.js

I added a Description Text for the Category Menu :)

Description for Ticket Category Menu

---

config/config.example.jsonc
utils/close.js

If closeTicketCategoryId is set then the Bot will move the closed ticket to another category f.e. "Closed Tickets"

Move closed ticket to another category

---

events/interactionCreate.js

Allow users to choose whenever or not to have a description

Choose to put a description

---

config/config.example.jsonc
events/interactionCreate.js

I'm a beginner with js but it works :)

Added rolesWhoCanNotCreateTickets

---

events/ready.js

Fixed when the message does not exist the bot sends the message automatically

Fixed when the message does not exist the bot sends the message automatically

---

.eslintignore
.eslintrc.js
.prettierignore
.prettierrc
commands/add.js
commands/claim.js
commands/close.js
commands/remove.js
config/config.example.jsonc
config/token.example.json
deploy-commands.js
events/interactionCreate.js
events/ready.js
index.js
locales/de.json
locales/fr.json
locales/main.json
package.json
utils/claim.js
utils/close.js
utils/close_askReason.js
utils/delete.js
utils/logs.js

Adding **EsLint** and **Prettier** to the project with some scripts in package.json to better work on the code.
Also adding ignore files for both.

✨ Introduce EsLint and Prettier config

---

locales/tr.json

I added Turkish language support

Add Turkish Language Support

---

locales/fr.json

Edit typo in french language

---

locales/cs.json

I copied main.json into a new cs.json file and translated these files into my language (Czech)

I added another language - Czech

---

utils/logs.js

Fix logs.js

---

src/events/ready.ts

Fixes #180
This PR fixes a crash issue that is caused by NodeJS Engine bug.

Temp fix for engine bug

---

src/utils/close.ts

Fix path of closeTicketCategoryId to right parent

fix: move channel after close

---

src/events/interactionCreate.ts

Fixed maxTicketOpened

---

.gitignore
docker_run.sh
package-lock.json
package.json

Some user seems to experience package conflict when install them. To avoid this issue, I've committed `package-lock.json` which contains all the current package installation state. This should hopefully avoid this issue.
While at it, I've also did dependency upgrade.
The alternative solution is to use yarn, which I'm not sure if you would like to.

Dependency Upgrade

---

locales/el.json

I have translated the locales to greek as well.

Greek Translation

---

locales/de.json

Translation Completed by user `Kekskruemel#2953` on discord.

Germany Translation

---

src/utils/close.ts
src/utils/createTicket.ts

Resolve issue https://discord.com/channels/592746774171484172/1132323312148676661/1132323312148676661

fix: createTicket missing json paths

---

config/config.example.jsonc
package-lock.json
src/events/ready.ts
src/structure/types.ts
src/utils/translation.ts

* Resolves #201
* `getSubValue` supports dot access for future work to keep params clean
* Package Upgrade

More Improvement

---

package-lock.json

chores: Dep Upgrade

---

.eslintignore
.prettierignore
docker_run.sh
package-lock.json
package.json
src/events/ready.ts

Modify to support flexible embed construction for `openTicket` and supports the feature `official_filp` (discord) is looking for

feat: Support flexible embed for openTicket

---

package-lock.json
package.json

Resolves #228
Resolves #226 
Resolves #225 
Resolves #222

chores: Update Dependency

---

locales/id.json
locales/my.json

This pull request introduces localization for our ticket system messages, adding support for two new languages:
*   **Indonesian (id-ID)**
* Filename: id.json
*   **Bahasa Melayu (ms-MY)**
* Filename: my.json

Added localization support for Indonesian and Malay languages

---

locales/it.json

#368 
to use this language, replace `it` with `main` in your config file (line no. 5)

Feat: Add localization support for italian language

---

package-lock.json
src/utils/claim.ts
src/utils/close.ts

Update general packages to latest

General Dependencies Upgrade
